Problem - 1: Array Creation:

In [ ]:
#1
import numpy as np

arr = np.zeros((2,2))

In [ ]:
#2
arr = np.ones((4,2))

In [ ]:
#3
def fill_arr(r,c,value):
    return np.full((r,c),value)

fill_arr(4,2,5)

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [ ]:
#4
def fill_zero_arr(arr):
    return np.zeros_like(arr)

arr1 = [[1,2],[3,4],[5,6]]
fill_zero_arr(arr1)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [ ]:
#5
def fill_zero_arr(arr):
    return np.ones_like(arr)

arr1 = [[1,2],[3,4],[5,6]]
fill_zero_arr(arr1)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
#6
new_list = [1,2,3,4]
converted_array = np.array(new_list)

converted_array

array([1, 2, 3, 4])

Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
#1
values_array = np.arange(10,50)

values_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
#2
value_array = np.arange(0,9)
matrix = value_array.reshape(3,3)

matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#3
identity_matrix = np.eye(3)

identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#4
random_array = np.random.random(30)
mean = random_array.mean()

print("Array: \n", random_array)
print("Mean: ", mean.item())

Array: 
 [0.82556765 0.00531289 0.85131302 0.63922758 0.84420926 0.06882079
 0.44180185 0.53597683 0.8055903  0.39520005 0.91014188 0.96327243
 0.02318123 0.14718026 0.55712993 0.36395233 0.51851298 0.68821702
 0.98805772 0.88054744 0.30181491 0.49781301 0.96913664 0.07574282
 0.83392357 0.89087163 0.66338502 0.38922979 0.71474813 0.88729114]
Mean:  0.5892390042365921


In [ ]:
#5
array = np.random.random((10,10))
minimum = array.min()
maximum = array.max()

print("Array: \n", array)
print("Minimum value: ", minimum)
print("Maximum value: ", maximum)

Array: 
 [[0.38231997 0.3160827  0.14491002 0.27343566 0.23871023 0.48564834
  0.23234464 0.92071895 0.64484287 0.89448351]
 [0.72872007 0.26381774 0.93691245 0.15253394 0.52191833 0.56539361
  0.06255197 0.38151266 0.56645427 0.81448425]
 [0.14132003 0.07522221 0.87376879 0.4053781  0.56063019 0.2153533
  0.87677958 0.81857016 0.20936389 0.93588747]
 [0.45175668 0.588942   0.55957091 0.50729299 0.74659889 0.73605056
  0.67580008 0.10833053 0.01479831 0.41898022]
 [0.71865427 0.17348421 0.01698323 0.47142147 0.56375176 0.94472237
  0.5633314  0.36184507 0.75441034 0.59082718]
 [0.99720373 0.79908606 0.91675483 0.98617897 0.05137396 0.84820071
  0.957025   0.1930521  0.63805089 0.29281187]
 [0.82685574 0.73613213 0.93970476 0.30264295 0.55601935 0.42057343
  0.17656687 0.7395679  0.95215187 0.17032973]
 [0.45726081 0.75248658 0.16434971 0.65407554 0.93643107 0.41473932
  0.3662064  0.47580615 0.90282275 0.07675434]
 [0.90888309 0.47410276 0.26298259 0.82153553 0.86932189 0.16797041
  0.

In [ ]:
#6
zero_array = np.zeros(10)
print("Array before changing the 5th element: ", zero_array)

zero_array[4] = 1
print("Array after changing the 5th element: ", zero_array)

Array before changing the 5th element:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array after changing the 5th element:  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#7
arr = np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]

print("Array reversed is: ", reversed_arr)

Array reversed is:  [0 4 0 0 2 1]


In [ ]:
#8
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#9
array = np.zeros((8,8))
array[1::2, ::2] = 1
array[::2, 1::2] = 1

array

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

In [ ]:
#1
print(x+y)

[[ 6  8]
 [10 13]]


In [ ]:
#2
print(x-y)

[[-4 -4]
 [-4 -3]]


In [ ]:
#3
print(x*6)

[[ 6 12]
 [18 30]]


In [ ]:
#4
print(y ** 2)

[[25 36]
 [49 64]]


In [ ]:
#5
print ("Dot product between v and w: ", np.dot(v,w))
print ("Dot product between x and v: ", np.dot(x,v))
print ("Dot product between x and y: ", np.dot(x,y))

Dot product between v and w:  219
Dot product between x and v:  [29 77]
Dot product between x and y:  [[19 22]
 [50 58]]


In [ ]:
#6
print("x and y along row: \n", np.concatenate((x,y)))
print("\n\nv and w along column: \n", np.concatenate((v,w)))

x and y along row: 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]


v and w along column: 
 [ 9 10 11 12]


In [ ]:
#7
np.concatenate((x,v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

We get an error here because x has shape (2,2) while v has shape (2,). Since these arrays have different dimensionality they cannot be concatenated unless both have the same dimensions.

Problem - 4: Matrix Operations:

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [ ]:
#1.1

A_inv = np.linalg.inv(A)
result = A @ A_inv
result = np.round(result).astype(int)

identity = np.eye(2, dtype = int)

print("A * A^-1 =\n", result, "\nI =\n", identity)
if (np.array_equal(result, identity)):
  print("A * A^-1 = I")

In [ ]:
# 1.2

AB = A @ B
BA = B @ A

print("AB =\n", AB, "\n\nBA =\n", BA)
print("\n")
print("A * B = B * A:", np.array_equal(AB, BA))

In [ ]:
#1.3

LHS = (A @ B).T
RHS = B.T @ A.T

print("LHS =\n", LHS, "\nRHS =\n", RHS)
if (np.array_equal(LHS, RHS)):
  print("(A.B)T (LHS) = (B)T.(A)T (RHS)")

In [ ]:
# 2

"""
Equations:
2x - 3y + z = -1
 x - y + 2z = -3
3x + y -  z =  9

"""

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]], dtype=float)

B = np.array([-1, -3, 9], dtype=float)

# AX = B
# X = A^-1 . B
# Finding X using np.linalg.inv()

A_inverse = np.linalg.inv(A)
X = A_inverse @ B
print("Using inverse matrix method:\n x = {:.2f}\n y = {:.2f}\n z = {:.2f}".format(X[0], X[1], X[2]))

In [ ]:
#3

X_solve = np.linalg.solve(A, B)
print("Using np.linalg.sovle():\n x = {:.2f}\n y = {:.2f}\n z = {:.2f}".format(X[0], X[1], X[2]))

EXPERIMENT:

In [ ]:
import time

# python lists
list1 = list(range(1000000))
list2 = list(range(1000000))

# numpy arrays
array1 = np.arange(1000000)
array2 = np.arange(1000000)

In [ ]:
# 1

# python lists
start = time.time()
list_add = [list1[i] + list2[i] for i in range(1000000)]
end = time.time()
print("Time for element-wise addition of python lists:", end - start, "s")

# numpy arrays
start = time.time()
array_add = array1 + array2
end = time.time()

print("Time for element-wise addition of numpy arrays:", end - start, "s")

In [ ]:
# 2

# python lists
start = time.time()
list_multiply = [list1[i] * list2[i] for i in range(1000000)]
end = time.time()
print("Time for element-wise multiplication of python lists:", end - start, "s")

# numpy arrays
start = time.time()
array_multiply = array1 * array2
end = time.time()

print("Time for element-wise multiplication of numpy arrays:", end - start, "s")

In [ ]:
# 3

# python lists
start = time.time()
list_dot = sum(list1[i] * list2[i] for i in range(1000000))
end = time.time()
print("Time for dot-product of python lists:", end - start, end="s\n")

# numpy arrays
start = time.time()
array_dot = np.dot(array1, array2)
end = time.time()

print("Time for dot-product of numpy arrays:", end - start, end="s\n")

In [ ]:
# 4

# python matrices
python1 = [[1 for _ in range(1000)] for _ in range(1000)]
python2 = [[1 for _ in range(1000)] for _ in range(1000)]
start = time.time()
python3 = [[sum(python1[i][k] * python2[k][j] for k in range(1000))
           for j in range(1000)] for i in range(1000)]
end = time.time()

print("Time for python matrix multiplication:", end - start, "s")

# numpy matrices
np1 = np.ones((1000, 1000))
np2 = np.ones((1000, 1000))

start = time.time()
np3 = np1 @ np2
end = time.time()

print("Time for numpy matrix multiplication:", end - start, "s")